### ISSUE TITLE
Roboko crashes randomly

### ISSUE THREAD

**Issue by Thibaut120094** [0x010C/Roboko#25]
``` python
Traceback (most recent call last):
  File "Roboko.py", line 48, in <module>
    main()
  File "Roboko.py", line 44, in main
    rbk_irc.mybot(server, port, chan, pseudo, password, wait, version).start()
  File "/home/roboko/Roboko/ircbot.py", line 247, in start
    SimpleIRCClient.start(self)
  File "/home/roboko/Roboko/irclib.py", line 1114, in start
    self.ircobj.process_forever()
  File "/home/roboko/Roboko/irclib.py", line 229, in process_forever
    self.process_once(timeout)
  File "/home/roboko/Roboko/irclib.py", line 217, in process_once
    self.process_timeout()
  File "/home/roboko/Roboko/irclib.py", line 193, in process_timeout
    self.delayed_commands[0][1](*self.delayed_commands[0][2])
  File "/home/roboko/Roboko/Roboko_irc.py", line 179, in checker
    rbk_rc.process_once()
  File "/home/roboko/Roboko/Roboko_recentchanges.py", line 225, in process_once
    irc_rcv.process_once(0.2)
  File "/home/roboko/Roboko/irclib.py", line 214, in process_once
    self.process_data(i)
  File "/home/roboko/Roboko/irclib.py", line 183, in process_data
    c.process_data()
  File "/home/roboko/Roboko/irclib.py", line 581, in process_data
    self._handle_event(Event(command, prefix, target, [m]))
  File "/home/roboko/Roboko/irclib.py", line 604, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/home/roboko/Roboko/irclib.py", line 325, in _handle_event
    if handler[1](connection, event) == "NO MORE":
  File "/home/roboko/Roboko/Roboko_recentchanges.py", line 197, in analyse
    movedata = r_move.findall(message)[0]
IndexError: list index out of range
```

**Comment by Thibaut120094** [comment]
Autre bug :

``` python
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 31, in translate
    return translate_word_by_word(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 59, in translate_word_by_word
    return translate(message)
  File "/home/roboko/Roboko/Roboko_jisho.py", line 30, in translate
    if split or message == prev_translation:
RuntimeError: maximum recursion depth exceeded in cmp
```

**Comment by 0x010C** [comment]
Fixed
